apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ai-stack
  namespace: ai-stack
spec:
  dnsNames:
    - PLACEHOLDER_DOMAIN
  secretName: ai-stack-tls
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
